#!/usr/bin/env python3
"""Regenerate the GitHub stats block in README.md.

Replaces the shared github-readme-stats.vercel.app cards, which cannot see
organization repositories: their top-langs endpoint queries
`ownerAffiliations: OWNER`, so Tiny Aya and Cohere Labs work is invisible to it.

Language shares are weighted by how many repositories use a language rather than
by bytes. Byte weighting is dominated by embedded notebook outputs (rendered
plots and base64 images), which put Jupyter Notebook at 95% and Python at 0.9%.
"""

import json
import os
import re
import sys
import urllib.error
import urllib.request
from collections import Counter

USER = "cataluna84"
# Orgs whose repos are authored by USER but are not returned by
# repositoriesContributedTo unless a commit is attributed to them.
EXTRA_ORGS = ["tiny-aya-simultaneous-translation"]
LANG_COUNT = 8
BAR_WIDTH = 22

API = "https://api.github.com/graphql"
START = "<!-- STATS:START -->"
END = "<!-- STATS:END -->"


def gql(query, variables=None):
    token = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")
    if not token:
        sys.exit("GITHUB_TOKEN or GH_TOKEN must be set")
    body = json.dumps({"query": query, "variables": variables or {}}).encode()
    req = urllib.request.Request(
        API,
        data=body,
        headers={
            "Authorization": f"bearer {token}",
            "Content-Type": "application/json",
            "User-Agent": f"{USER}-profile-stats",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            payload = json.load(r)
    except urllib.error.HTTPError as e:
        sys.exit(f"GraphQL HTTP {e.code}: {e.read().decode()[:400]}")
    if "errors" in payload:
        sys.exit(f"GraphQL errors: {payload['errors']}")
    return payload["data"]


REPO_FIELDS = """
  nameWithOwner
  stargazerCount
  primaryLanguage { name }
  languages(first: 20, orderBy: {field: SIZE, direction: DESC}) {
    edges { size node { name } }
  }
"""

Q_PROFILE = """
query($user: String!) {
  user(login: $user) {
    followers { totalCount }
    contributionsCollection {
      totalCommitContributions
      totalPullRequestContributions
      contributionCalendar { totalContributions }
    }
    pullRequests(states: MERGED) { totalCount }
    repositories(first: 100, ownerAffiliations: OWNER, isFork: false, privacy: PUBLIC) {
      totalCount
      nodes { %s }
    }
    repositoriesContributedTo(
      first: 100
      includeUserRepositories: false
      privacy: PUBLIC
      contributionTypes: [COMMIT, PULL_REQUEST, REPOSITORY]
    ) {
      totalCount
      nodes { %s }
    }
  }
}
""" % (REPO_FIELDS, REPO_FIELDS)

Q_ORG = """
query($org: String!) {
  organization(login: $org) {
    repositories(first: 100, isFork: false, privacy: PUBLIC) {
      nodes { %s }
    }
  }
}
""" % REPO_FIELDS


def collect():
    user = gql(Q_PROFILE, {"user": USER})["user"]
    own = user["repositories"]["nodes"]
    contributed = user["repositoriesContributedTo"]["nodes"]

    org_repos = []
    for org in EXTRA_ORGS:
        data = gql(Q_ORG, {"org": org}).get("organization")
        if data:
            org_repos += data["repositories"]["nodes"]

    # Deduplicate: a repo can appear in both the contributed and org queries.
    repos = {r["nameWithOwner"]: r for r in own + contributed + org_repos}
    return user, own, repos


def render(user, own, repos):
    contrib = user["contributionsCollection"]
    stars = sum(r["stargazerCount"] for r in own)

    lang_repos = Counter()
    for repo in repos.values():
        for edge in repo["languages"]["edges"]:
            lang_repos[edge["node"]["name"]] += 1

    total_repos = len(repos)
    top = lang_repos.most_common(LANG_COUNT)

    lines = [
        START,
        "",
        "<!-- Generated by scripts/gen_stats.py. Do not edit by hand. -->",
        "",
        "| | |",
        "|---|---|",
        f"| Contributions (last year) | **{contrib['contributionCalendar']['totalContributions']:,}** |",
        f"| Commits (last year) | **{contrib['totalCommitContributions']:,}** |",
        f"| Pull requests merged | **{user['pullRequests']['totalCount']:,}** |",
        f"| Stars earned | **{stars:,}** |",
        f"| Followers | **{user['followers']['totalCount']:,}** |",
        f"| Repositories | **{total_repos}** "
        f"({user['repositories']['totalCount']} personal, "
        f"{total_repos - user['repositories']['totalCount']} org &amp; collaborative) |",
        "",
        f"**Languages** — share of the {total_repos} repositories each language appears in:",
        "",
        "```text",
    ]

    width = max(len(name) for name, _ in top)
    for name, count in top:
        pct = 100 * count / total_repos
        filled = round(BAR_WIDTH * count / top[0][1])
        bar = "█" * filled + "░" * (BAR_WIDTH - filled)
        lines.append(f"{name:<{width}}  {bar}  {pct:5.1f}%  ({count} repos)")

    lines += [
        "```",
        "",
        "<sub>Weighted by repository count, not bytes: notebook files embed their "
        "rendered outputs, so byte-weighted shares measure figure size rather than "
        "code. Includes organization and collaborative repositories.</sub>",
        "",
        END,
    ]
    return "\n".join(lines)


def main():
    readme = os.path.join(os.path.dirname(__file__), os.pardir, "README.md")
    readme = os.path.abspath(readme)
    with open(readme, encoding="utf-8") as f:
        text = f.read()

    if START not in text or END not in text:
        sys.exit(f"markers {START} / {END} not found in {readme}")

    user, own, repos = collect()
    block = render(user, own, repos)
    updated = re.sub(
        re.escape(START) + ".*?" + re.escape(END), lambda _: block, text, flags=re.S
    )

    if updated == text:
        print("stats unchanged")
        return

    with open(readme, "w", encoding="utf-8") as f:
        f.write(updated)
    print(f"stats updated across {len(repos)} repositories")


if __name__ == "__main__":
    main()
